<a href="https://colab.research.google.com/github/asmaanjum0910-sketch/data-science-60-days/blob/main/Datascience.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

importing pandas

In [ ]:
import pandas as pd

In [ ]:
l=[1,2,3,4,5]
df=pd.Series(l)
df

0    1
1    2
2    3
3    4
4    5
dtype: int64

Labels

In [ ]:
a=[70,80,90,100]
df=pd.Series(a,index=['row 1', 'row 2', 'row 3', 'row 4'])
df

row 1     70
row 2     80
row 3     90
row 4    100
dtype: int64

pandas series(dictionaries to dataframe)

In [ ]:
d={
    'Name' : 'Asma',
    'Gender' : 'F',
    'Contact' : 'ABCD'
}

df=pd.Series(d)
df

Name       Asma
Gender        F
Contact    ABCD
dtype: object

selecting onlt some items from dataframe while converting

In [ ]:
d={
    'Name' : 'Asma',
    'Gender' : 'F',
    'Contact' : 'ABCD'
}
df=pd.Series(d,index=['Name','Contact'])
df

Name       Asma
Contact    ABCD
dtype: object

Dataframe

In [ ]:
d={
    'Names':['Asma','sana','Abbu'],
    'Age':[20,25,29],
    'Country':['USA','CANADA','QATAR']

}
df=pd.DataFrame(d)
df

  Names  Age Country
0  Asma   20     USA
1  sana   25  CANADA
2  Abbu   29   QATAR

practice - Build a DataFrame of 10 students in 6 subjects.

In [ ]:
d = {
    'Students': ['Asma', 'Abbu', 'Sana', 'Arun', 'Hari',
                 'Tina', 'Ravi', 'Humar', 'Murali', 'Hina'],

    'Subject': ['Hindi', 'English', 'Maths', 'Science', 'Social',
                'Drawing', 'Hindi', 'English', 'Maths', 'Science'],

    'Marks': [20, 21, 22, 23, 24, 25, 26, 27, 26, 23]
}

df = pd.DataFrame(d)

print(df)

  Students  Subject  Marks
0     Asma    Hindi     20
1     Abbu  English     21
2     Sana    Maths     22
3     Arun  Science     23
4     Hari   Social     24
5     Tina  Drawing     25
6     Ravi    Hindi     26
7    Humar  English     27
8   Murali    Maths     26
9     Hina  Science     23

practice -2

In [ ]:
d= {

    'name': ['Rahul','Rohan','Akash','Ajay', 'Amit', 'Raj'],

    'Subject 1 marks': [34,35,36,34,35,36],

    'Subject 2 marks': [34,35,36,34,35,36],

    'Subject 3 marks': [34,35,36,34,35,36],

    'Subject 4 marks': [34,35,36,34,35,36],

    'Subject 5 marks': [34,35,36,34,35,36],

    'Subject 6 marks': [34,35,36,34,35,36],

}

df=pd.DataFrame(d)

df

,name,Subject 1 marks,Subject 2 marks,Subject 3 marks,Subject 4 marks,Subject 5 marks,Subject 6 marks
0,Rahul,34,34,34,34,34,34
1,Rohan,35,35,35,35,35,35
2,Akash,36,36,36,36,36,36
3,Ajay,34,34,34,34,34,34
4,Amit,35,35,35,35,35,35
5,Raj,36,36,36,36,36,36

Convert CSV file to Dataframe

In [ ]:
df = pd.read_csv('IndianHouses.csv')
df

,Area,BHK,Bathroom,Furnishing,Locality,Parking,Price,Status,Transaction,Type,Per_Sqft
0,800.0,3,2.0,Semi-Furnished,Rohini Sector 25,1.0,6500000,Ready_to_move,New_Property,Builder_Floor,NaN
1,750.0,2,2.0,Semi-Furnished,"J R Designers Floors, Rohini Sector 24",1.0,5000000,Ready_to_move,New_Property,Apartment,6667.0
2,950.0,2,2.0,Furnished,"Citizen Apartment, Rohini Sector 13",1.0,15500000,Ready_to_move,Resale,Apartment,6667.0
3,600.0,2,2.0,Semi-Furnished,Rohini Sector 24,1.0,4200000,Ready_to_move,Resale,Builder_Floor,6667.0
4,650.0,2,2.0,Semi-Furnished,Rohini Sector 24 carpet area 650 sqft status R...,1.0,6200000,Ready_to_move,New_Property,Builder_Floor,6667.0
...,...,...,...,...,...,...,...,...,...,...,...
1254,4118.0,4,5.0,Unfurnished,Chittaranjan Park,3.0,55000000,Ready_to_move,New_Property,Builder_Floor,12916.0
1255,1050.0,3,2.0,Semi-Furnished,Chittaranjan Park,3.0,12500000,Ready_to_move,Resale,Builder_Floor,12916.0
1256,875.0,3,3.0,Semi-Furnished,Chittaranjan Park,3.0,17500000,Ready_to_move,New_Property,Builder_Floor,12916.0
1257,990.0,2,2.0,Unfurnished,Chittaranjan Park Block A,1.0,11500000,Ready_to_move,Resale,Builder_Floor,12916.0
1258,11050.0,3,3.0,Unfurnished,Chittaranjan Park,1.0,18500000,Ready_to_move,New_Property,Builder_Floor,12916.0

Find the most expensive house
 print the price

In [ ]:
df['Price'].max()

240000000

complete row having the highest price

In [ ]:
df.loc[df['Price'].idxmax()]

Area                   8000.0
BHK                         4
Bathroom                  5.0
Furnishing     Semi-Furnished
Locality         Lajpat Nagar
Parking                   1.0
Price               240000000
Status          Ready_to_move
Transaction      New_Property
Type            Builder_Floor
Per_Sqft              22000.0
Name: 57, dtype: object

all rows having the highest price

In [ ]:
df[df['Price'] == df['Price'].max()]

,Area,BHK,Bathroom,Furnishing,Locality,Parking,Price,Status,Transaction,Type,Per_Sqft
57,8000.0,4,5.0,Semi-Furnished,Lajpat Nagar,1.0,240000000,Ready_to_move,New_Property,Builder_Floor,22000.0
109,8000.0,4,5.0,Semi-Furnished,Lajpat Nagar,1.0,240000000,Ready_to_move,New_Property,Builder_Floor,20000.0

find the area of the most expensive house

In [ ]:
df.loc[df['Price'].idxmax(), 'Area']
print(df)

         Area  BHK  Bathroom      Furnishing  \
0       800.0    3       2.0  Semi-Furnished
1       750.0    2       2.0  Semi-Furnished
2       950.0    2       2.0       Furnished
3       600.0    2       2.0  Semi-Furnished
4       650.0    2       2.0  Semi-Furnished
...       ...  ...       ...             ...
1254   4118.0    4       5.0     Unfurnished
1255   1050.0    3       2.0  Semi-Furnished
1256    875.0    3       3.0  Semi-Furnished
1257    990.0    2       2.0     Unfurnished
1258  11050.0    3       3.0     Unfurnished

                                               Locality  Parking     Price  \
0                                      Rohini Sector 25      1.0   6500000
1                J R Designers Floors, Rohini Sector 24      1.0   5000000
2                   Citizen Apartment, Rohini Sector 13      1.0  15500000
3                                      Rohini Sector 24      1.0   4200000
4     Rohini Sector 24 carpet area 650 sqft status R...      1.0   6200000
...                                                 ...      ...       ...
1254                                  Chittaranjan Park      3.0  55000000
1255                                  Chittaranjan Park      3.0  12500000
1256                                  Chittaranjan Park      3.0  17500000
1257                          Chittaranjan Park Block A      1.0  11500000
1258                                  Chittaranjan Park      1.0  18500000

             Status   Transaction           Type  Per_Sqft
0     Ready_to_move  New_Property  Builder_Floor       NaN
1     Ready_to_move  New_Property      Apartment    6667.0
2     Ready_to_move        Resale      Apartment    6667.0
3     Ready_to_move        Resale  Builder_Floor    6667.0
4     Ready_to_move  New_Property  Builder_Floor    6667.0
...             ...           ...            ...       ...
1254  Ready_to_move  New_Property  Builder_Floor   12916.0
1255  Ready_to_move        Resale  Builder_Floor   12916.0
1256  Ready_to_move  New_Property  Builder_Floor   12916.0
1257  Ready_to_move        Resale  Builder_Floor   12916.0
1258  Ready_to_move  New_Property  Builder_Floor   12916.0

[1259 rows x 11 columns]

In [ ]:
hp = 6500000
row = 0
for i in df['Area']:
  if df.loc[row, 'Price'] == hp:
    print(df.loc[row, 'Area'])
  row += 1

800.0
850.0
720.0
970.0
1017.0
747.0
900.0
1000.0
594.0
1750.0
1250.0
1100.0
1000.0
650.0
750.0
855.0
900.0
945.0

Head

In [ ]:
df.head(10)

,Area,BHK,Bathroom,Furnishing,Locality,Parking,Price,Status,Transaction,Type,Per_Sqft
0,800.0,3,2.0,Semi-Furnished,Rohini Sector 25,1.0,6500000,Ready_to_move,New_Property,Builder_Floor,NaN
1,750.0,2,2.0,Semi-Furnished,"J R Designers Floors, Rohini Sector 24",1.0,5000000,Ready_to_move,New_Property,Apartment,6667.0
2,950.0,2,2.0,Furnished,"Citizen Apartment, Rohini Sector 13",1.0,15500000,Ready_to_move,Resale,Apartment,6667.0
3,600.0,2,2.0,Semi-Furnished,Rohini Sector 24,1.0,4200000,Ready_to_move,Resale,Builder_Floor,6667.0
4,650.0,2,2.0,Semi-Furnished,Rohini Sector 24 carpet area 650 sqft status R...,1.0,6200000,Ready_to_move,New_Property,Builder_Floor,6667.0
5,1300.0,4,3.0,Semi-Furnished,Rohini Sector 24,1.0,15500000,Ready_to_move,New_Property,Builder_Floor,6667.0
6,1350.0,4,3.0,Semi-Furnished,Rohini Sector 24,1.0,10000000,Ready_to_move,Resale,Builder_Floor,6667.0
7,650.0,2,2.0,Semi-Furnished,"Delhi Homes, Rohini Sector 24",1.0,4000000,Ready_to_move,New_Property,Apartment,6154.0
8,985.0,3,3.0,Unfurnished,Rohini Sector 21,1.0,6800000,Almost_ready,New_Property,Builder_Floor,6154.0
9,1300.0,4,4.0,Semi-Furnished,Rohini Sector 22,1.0,15000000,Ready_to_move,New_Property,Builder_Floor,6154.0

Info

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1259 entries, 0 to 1258
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Area         1259 non-null   float64
 1   BHK          1259 non-null   int64
 2   Bathroom     1257 non-null   float64
 3   Furnishing   1254 non-null   object
 4   Locality     1259 non-null   object
 5   Parking      1226 non-null   float64
 6   Price        1259 non-null   int64
 7   Status       1259 non-null   object
 8   Transaction  1259 non-null   object
 9   Type         1254 non-null   object
 10  Per_Sqft     1018 non-null   float64
dtypes: float64(4), int64(2), object(5)
memory usage: 108.3+ KB

In [ ]:
df.describe()

,Area,BHK,Bathroom,Parking,Price,Per_Sqft
count,1259.000000,1259.000000,1257.000000,1226.000000,1.259000e+03,1018.000000
mean,1466.452724,2.796664,2.556086,1.935563,2.130670e+07,15690.136542
std,1568.055040,0.954425,1.042220,6.279212,2.560115e+07,21134.738568
min,28.000000,1.000000,1.000000,1.000000,1.000000e+06,1259.000000
25%,800.000000,2.000000,2.000000,1.000000,5.700000e+06,6364.000000
50%,1200.000000,3.000000,2.000000,1.000000,1.420000e+07,11291.500000
75%,1700.000000,3.000000,3.000000,2.000000,2.550000e+07,18000.000000
max,24300.000000,10.000000,7.000000,114.000000,2.400000e+08,183333.000000

duplicate - returns row number with true if finds the duplictes

In [ ]:
print(df.duplicated().to_string())

0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19      False
20      False
21      False
22      False
23      False
24      False
25      False
26      False
27      False
28      False
29      False
30      False
31      False
32      False
33      False
34      False
35      False
36      False
37      False
38      False
39      False
40      False
41      False
42      False
43      False
44      False
45      False
46      False
47      False
48      False
49      False
50      False
51      False
52      False
53      False
54      False
55      False
56      False
57      False
58      False
59      False
60      False
61      False
62      False
63      False
64      False
65      False
66      False
67      False
68      False
69      False
70      False
71      False
72      False
73      False
74      False
75      False
76      False
77      False
78      False
79      False
80      False
81      False
82      False
83      False
84       True
85      False
86      False
87      False
88      False
89      False
90      False
91      False
92       True
93      False
94      False
95      False
96      False
97      False
98      False
99      False
100     False
101     False
102     False
103     False
104     False
105     False
106     False
107     False
108     False
109     False
110      True
111     False
112     False
113     False
114     False
115     False
116     False
117     False
118     False
119     False
120      True
121     False
122      True
123     False
124     False
125     False
126     False
127     False
128     False
129     False
130     False
131     False
132     False
133     False
134     False
135     False
136     False
137     False
138     False
139     False
140     False
141     False
142     False
143     False
144     False
145     False
146     False
147     False
148     False
149      True
150     False
151     False
152     False
153     False
154     False
155     False
156     False
157     False
158     False
159     False
160     False
161     False
162     False
163     False
164     False
165     False
166     False
167     False
168     False
169     False
170     False
171     False
172     False
173     False
174     False
175     False
176     False
177     False
178     False
179     False
180     False
181      True
182     False
183     False
184     False
185     False
186     False
187     False
188     False
189     False
190     False
191     False
192     False
193     False
194     False
195     False
196     False
197     False
198     False
199     False
200     False
201     False
202     False
203     False
204     False
205     False
206     False
207     False
208     False
209     False
210      True
211     False
212     False
213     False
214     False
215     False
216      True
217     False
218      True
219     False
220     False
221      True
222     False
223     False
224     False
225     False
226     False
227     False
228     False
229     False
230     False
231     False
232     False
233     False
234     False
235     False
236     False
237     False
238     False
239     False
240     False
241     False
242     False
243     False
244     False
245     False
246     False
247     False
248     False
249     False
250     False
251     False
252     False
253     False
254     False
255     False
256     False
257     False
258     False
259     False
260     False
261     False
262     False
263     False
264     False
265     False
266     False
267     False
268     False
269     False
270     False
271     False
272     False
273     False
274     False
275     False
276     False
277     False
278     False
279     False
280     False
281     False
282     False
283     False
284     False
285     False
286     False
287     False
288     False
289     False
290     False
291     False
292     False
293     False
294     False
295     False
296     False
297     False
298     False
299     False
300     False
301     False
302     False
303     False
304     False
305     False
306     False
307     False
308     False
309     False
310     False
311     False
312     False
313     False
314     False
315     False
316     False
317     False
318     False
319     False
320     False
321     False
322     False
323     False
324     False
325     False
326     False
327     False
328     False
329     False
330     False
331     False
332     False
333     False
334     False
335     False
336     False
337     False
338     False
339     False
340     False
341     False
342     False
343     False
344     False
345     False
346     False
347     False
348     False
349     False
350     False
351     False
352     False
353     False
354     False
355     False
356     False
357     False
358     False
359     False
360     False
361     False
362     False
363     False
364     False
365     False
366     False
367     False
368     False
369     False
370     False
371     False
372     False
373     False
374     False
375     False
376     False
377     False
378     False
379     False
380     False
381     False
382     False
383     False
384     False
385     False
386     False
387     False
388     False
389     False
390      True
391      True
392      True
393      True
394     False
395     False
396     False
397     False
398     False
399     False
400     False
401     False
402     False
403     False
404     False
405     False
406     False
407     False
408     False
409     False
410     False
411     False
412     False
413     False
414     False
415     False
416     False
417     False
418     False
419      True
420      True
421     False
422     False
423     False
424     False
425     False
426     False
427     False
428     False
429     False
430     False
431     False
432     False
433     False
434     False
435     False
436     False
437     False
438      True
439     False
440     False
441     False
442     False
443     False
444     False
445     False
446     False
447     False
448     False
449     False
450     False
451     False
452     False
453     False
454     False
455     False
456     False
457     False
458     False
459     False
460     False
461     False
462     False
463     False
464     False
465     False
466     False
467     False
468     False
469     False
470     False
471     False
472     False
473     False
474     False
475     False
476     False
477     False
478     False
479      True
480      True
481      True
482      True
483      True
484      True
485      True
486      True
487      True
488      True
489      True
490      True
491      True
492      True
493      True
494      True
495      True
496      True
497      True
498      True
499      True
500      True
501      True
502      True
503      True
504      True
505      True
506      True
507      True
508      True
509     False
510     False
511     False
512     False
513     False
514     False
515     False
516     False
517     False
518     False
519     False
520     False
521     False
522     False
523     False
524     False
525     False
526     False
527     False
528     False
529     False
530     False
531     False
532     False
533     False
534     False
535     False
536      True
537      True
538     False
539     False
540     False
541     False
542     False
543     False
544     False
545     False
546     False
547     False
548     False
549     False
550     False
551     False
552     False
553     False
554     False
555     False
556     False
557     False
558     False
559     False
560     False
561     False
562     False
563     False
564     False
565     False
566     False
567     False
568     False
569     False
570     False
571     False
572     False
573     False
574     False
575     False
576     False
577     False
578     False
579     False
580     False
581     False
582     False
583     False
584     False
585     False
586     False
587     False
588     False
589     False
590     False
591     False
592     False
593     False
594     False
595     False
596     False
597     False
598     False
599     False
600     False
601     False
602     False
603     False
604     False
605     False
606     False
607     False
608     False
609     False
610     False
611     False
612     False
613     False
614     False
615     False
616     False
617     False
618     False
619     False
620     False
621     False
622     False
623     False
624     False
625     False
626     False
627     False
628     False
629     False
630     False
631     False
632     False
633     False
634     False
635     False
636     False
637     False
638     False
639     False
640     False
641     False
642     False
643     False
644     False
645     False
646     False
647     False
648     False
649     False
650     False
651     False
652     False
653     False
654     False
655     False
656     False
657     False
658     False
659     False
660     False
661     False
662     False
663     False
664     False
665     False
666     False
667     False
668     False
669     False
670     False
671     False
672     False
673     False
674     False
675     False
676     False
677     False
678     False
679     False
680     False
681     False
682     False
683     False
684     False
685     False
686     False
687     False
688     False
689     False
690     False
691     False
692     False
693     False
694     False
695     False
696     False
697     False
698     False
699     False
700     False
701     False
702     False
703     False
704     False
705     False
706     False
707     False
708     False
709     False
710     False
711     False
712     False
713     False
714     False
715     False
716     False
717     False
718     False
719     False
720     False
721     False
722     False
723     False
724     False
725     False
726     False
727     False
728     False
729     False
730     False
731     False
732     False
733     False
734     False
735     False
736     False
737     False
738     False
739     False
740     False
741     False
742     False
743     False
744     False
745     False
746     False
747     False
748     False
749     False
750     False
751     False
752     False
753     False
754     False
755     False
756     False
757     False
758     False
759     False
760     False
761     False
762     False
763     False
764     False
765     False
766     False
767     False
768      True
769     False
770     False
771     False
772     False
773     False
774     False
775     False
776     False
777     False
778     False
779     False
780     False
781     False
782     False
783     False
784     False
785     False
786     False
787     False
788     False
789     False
790     False
791     False
792     False
793     False
794     False
795     False
796     False
797     False
798     False
799     False
800     False
801     False
802     False
803     False
804     False
805     False
806     False
807     False
808     False
809     False
810     False
811     False
812     False
813     False
814     False
815     False
816     False
817     False
818     False
819     False
820     False
821     False
822     False
823     False
824     False
825     False
826     False
827     False
828     False
829     False
830     False
831     False
832     False
833     False
834     False
835     False
836     False
837     False
838     False
839     False
840     False
841     False
842     False
843     False
844     False
845     False
846     False
847     False
848     False
849     False
850     False
851     False
852     False
853     False
854     False
855     False
856     False
857     False
858     False
859     False
860     False
861     False
862     False
863     False
864     False
865     False
866     False
867     False
868     False
869     False
870     False
871     False
872     False
873     False
874     False
875     False
876     False
877     False
878     False
879     False
880     False
881     False
882     False
883     False
884     False
885     False
886     False
887     False
888     False
889     False
890     False
891     False
892     False
893     False
894     False
895     False
896     False
897     False
898     False
899     False
900     False
901     False
902     False
903     False
904     False
905     False
906     False
907     False
908     False
909     False
910     False
911     False
912     False
913     False
914     False
915     False
916     False
917     False
918     False
919     False
920     False
921     False
922     False
923     False
924     False
925     False
926     False
927     False
928     False
929     False
930     False
931     False
932     False
933     False
934     False
935     False
936     False
937     False
938     False
939     False
940     False
941     False
942     False
943     False
944     False
945     False
946     False
947     False
948     False
949     False
950     False
951     False
952     False
953     False
954     False
955     False
956     False
957     False
958     False
959     False
960     False
961     False
962     False
963     False
964     False
965     False
966     False
967     False
968     False
969     False
970     False
971     False
972     False
973     False
974     False
975     False
976     False
977     False
978     False
979     False
980     False
981     False
982     False
983     False
984     False
985     False
986     False
987     False
988     False
989     False
990     False
991     False
992     False
993     False
994     False
995     False
996     False
997     False
998     False
999     False
1000    False
1001    False
1002    False
1003    False
1004    False
1005    False
1006    False
1007    False
1008    False
1009    False
1010    False
1011    False
1012    False
1013    False
1014    False
1015    False
1016    False
1017    False
1018    False
1019    False
1020    False
1021    False
1022    False
1023    False
1024    False
1025    False
1026     True
1027    False
1028    False
1029    False
1030    False
1031    False
1032    False
1033     True
1034    False
1035    False
1036    False
1037    False
1038    False
1039    False
1040    False
1041    False
1042    False
1043    False
1044    False
1045    False
1046    False
1047    False
1048    False
1049    False
1050    False
1051    False
1052    False
1053    False
1054    False
1055    False
1056    False
1057    False
1058    False
1059    False
1060    False
1061    False
1062    False
1063    False
1064    False
1065    False
1066    False
1067    False
1068    False
1069    False
1070    False
1071    False
1072    False
1073    False
1074    False
1075    False
1076    False
1077    False
1078    False
1079    False
1080    False
1081    False
1082    False
1083    False
1084    False
1085    False
1086    False
1087    False
1088    False
1089    False
1090    False
1091    False
1092    False
1093    False
1094    False
1095    False
1096    False
1097    False
1098    False
1099    False
1100    False
1101    False
1102    False
1103    False
1104    False
1105    False
1106    False
1107    False
1108    False
1109    False
1110    False
1111    False
1112    False
1113    False
1114    False
1115    False
1116    False
1117    False
1118    False
1119    False
1120    False
1121    False
1122    False
1123    False
1124    False
1125    False
1126    False
1127    False
1128    False
1129    False
1130    False
1131    False
1132    False
1133    False
1134    False
1135    False
1136    False
1137    False
1138    False
1139     True
1140     True
1141     True
1142     True
1143     True
1144     True
1145     True
1146     True
1147     True
1148     True
1149     True
1150     True
1151     True
1152     True
1153     True
1154     True
1155     True
1156     True
1157     True
1158     True
1159     True
1160     True
1161     True
1162     True
1163     True
1164     True
1165     True
1166     True
1167     True
1168     True
1169    False
1170    False
1171    False
1172    False
1173    False
1174    False
1175    False
1176    False
1177    False
1178    False
1179    False
1180    False
1181    False
1182    False
1183    False
1184    False
1185    False
1186    False
1187    False
1188    False
1189    False
1190    False
1191    False
1192    False
1193    False
1194    False
1195    False
1196    False
1197    False
1198    False
1199    False
1200    False
1201    False
1202    False
1203    False
1204    False
1205    False
1206    False
1207    False
1208    False
1209    False
1210    False
1211    False
1212    False
1213    False
1214    False
1215    False
1216    False
1217    False
1218    False
1219    False
1220    False
1221    False
1222    False
1223    False
1224    False
1225    False
1226    False
1227    False
1228    False
1229    False
1230    False
1231    False
1232    False
1233    False
1234    False
1235    False
1236    False
1237    False
1238    False
1239    False
1240    False
1241    False
1242    False
1243    False
1244    False
1245    False
1246    False
1247    False
1248    False
1249    False
1250    False
1251    False
1252    False
1253    False
1254    False
1255    False
1256    False
1257    False
1258    False

remove duplicates

In [ ]:
print(df.drop_duplicates().to_string())

            Area  BHK  Bathroom      Furnishing                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Locality  Parking      Price         Status   Transaction           Type  Per_Sqft
0       800.0000    3       2.0  Semi-Furnished                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Rohini Sector 25      1.0    6500000  Ready_to_move  New_Property  Builder_Floor       NaN
1       750.0000    2       2.0  Semi-Furnished                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       J R Designers Floors, Rohini Sector 24      1.0    5000000  Ready_to_move  New_Property      Apartment    6667.0
2       950.0000    2       2.0       Furnished                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Citizen Apartment, Rohini Sector 13      1.0   15500000  Ready_to_move        Resale      Apartment    6667.0
3       600.0000    2       2.0  Semi-Furnished                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Rohini Sector 24      1.0    4200000  Ready_to_move        Resale  Builder_Floor    6667.0
4       650.0000    2       2.0  Semi-Furnished                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Rohini Sector 24 carpet area 650 sqft status Ready to Move floor 4 out of 4 floors transaction New Property furnishing Semi-Furnished facing East overlooking Garden/Park, Main Road car parking 1 Open bathroom 2 balcony 1 ownership Freehold Newly Constructed Property Newly Constructed Property East Facing Property 2BHK Newly build property for Sale. A House is waiting for a Friendly Family to make it a lovely home.So please come and make his house feel alive once again. read more Contact Agent View Phone No. Share Feedback Garima properties Certified Agent Trusted by Users Genuine Listings Market Knowledge      1.0    6200000  Ready_to_move  New_Property  Builder_Floor    6667.0
5      1300.0000    4       3.0  Semi-Furnished                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Rohini Sector 24      1.0   15500000  Ready_to_move  New_Property  Builder_Floor    6667.0
6      1350.0000    4       3.0  Semi-Furnished                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Rohini Sector 24      1.0   10000000  Ready_to_move        Resale  Builder_Floor    6667.0

correclation - gives metrics values
how two numerical columns are related to each other
| Correlation | Meaning                       |
| ----------: | ----------------------------- |
|      **+1** | Perfect positive relationship |
|    **+0.8** | Strong positive               |
|    **+0.5** | Moderate positive             |
|       **0** | No linear relationship        |
|    **-0.5** | Moderate negative             |
|    **-0.8** | Strong negative               |
|      **-1** | Perfect negative              |

In [ ]:
df = pd.read_csv('Diabetes-Dataset.csv')
# df.corr()

d = {
    'ages': [90, 89, 67, 45],
    'marks': [78, 90, 87, 100]
}
df = pd.DataFrame(d)
# df
df.corr()

FileNotFoundError: [Errno 2] No such file or directory: 'Diabetes-Dataset.csv'

specific 2 coloumns

In [ ]:
print(df['ages'].corr(df['marks']))

accessing specific dataframe
d=df.iloc[:,[0,1,2,5,6]] - rows,column (here we are choosing specfic colums)

In [ ]:
df = pd.read_csv('IndianHouses.csv')
d=df.iloc[:,[0,1,2,5,6]]
d.corr()

Build a new dataframe that will have the unique BHK values and their respective counts

In [ ]:
df=pd.read_csv('IndianHouses.csv')
d=df['BHK'].value_counts()
d

BHK
3     541
2     367
4     220
1      96
5      27
6       6
7       1
10      1
Name: count, dtype: int64

OR

In [ ]:
new_df = df.groupby('BHK').size().reset_index(name='Count')

print(new_df)

   BHK  Count
0    1     96
1    2    367
2    3    541
3    4    220
4    5     27
5    6      6
6    7      1
7   10      1

fetch all locality names that start with 'k'

In [27]:
df=df[df['Locality'].str.contains('^k', case=False, na=False)]
print(df['Locality'])

65                 Kunj Vihar Apartment, Dwarka Sector 12
83                         Karuna Vihar Apartment, Dwarka
219                           Kushwaha Homes, Uttam Nagar
223                Kunj Vihar Apartment, Dwarka Sector 12
237                                     Khanpur, Madangir
                              ...
1190                                    Kalkaji Extention
1191    Kalkaji super area 1000 sqft status Ready to M...
1194                                              Kalkaji
1195                                              Kalkaji
1197                                    Kalkaji Extention
Name: Locality, Length: 69, dtype: object

Get me the number of Ready to Move Apartments

In [40]:
ready_to_move_df = df[df['Status'] == 'Ready_to_move']
number_of_ready_to_move_apartments = len(ready_to_move_df)
print(number_of_ready_to_move_apartments)

68

OR

In [41]:
number_of_ready_to_move_apartments = (df['Status'] == 'Ready_to_move').sum()
print(number_of_ready_to_move_apartments)

68

Day01_Python_Basics.ipynb

In [1]:
a=8
b=6
sum=a+b
print(sum)

14